# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicmodel',
            name='image_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='comicmodel',
            name='cover',
            field=models.ImageField(upload_to='app/static', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='comicmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
