# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170824_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicmodel',
            name='description',
            field=models.TextField(default='Good comics!'),
        ),
        migrations.AddField(
            model_name='comicmodel',
            name='heroes_list',
            field=models.TextField(default='Good heroes!'),
        ),
    ]
