# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20170824_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic_UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comicmodel',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='Выбрать комикс'),
        ),
        migrations.AddField(
            model_name='comic_usermodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ComicModel'),
        ),
    ]
